package main

import (
	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
	"github.com/go-chi/jwtauth"
	"github.com/joseMarciano/pos-golang-expert/apis/configs/authconfig"
	_ "github.com/joseMarciano/pos-golang-expert/apis/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/joseMarciano/pos-golang-expert/apis/internal/entity/product"
	"github.com/joseMarciano/pos-golang-expert/apis/internal/entity/user"
	"github.com/joseMarciano/pos-golang-expert/apis/internal/infra/database"
	"github.com/joseMarciano/pos-golang-expert/apis/internal/infra/webserver/handlers"
	httpSwagger "github.com/swaggo/http-swagger"
	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
	"net/http"
)

func init() {
	println("Main")
}

// @title Swagger Example API
// @version 1.0
// @description This is a sample server Petstore server.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8080
// @BasePath /v2
// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name Authorization
func main() {
	//fmt.Println(databaseconfig.GetDbConfig())
	//fmt.Println(authconfig.GetAuthConfig())
	//fmt.Println(serverconfig.GetServerConfig())

	authConfiguration := authconfig.GetAuthConfig()

	db, err := gorm.Open(sqlite.Open("test.db"), &gorm.Config{})
	if err != nil {
		panic(err)
	}

	db.AutoMigrate(&user.User{}, &product.Product{})
	productDB := database.NewProductDB(db)
	productHandler := handlers.NewProductHandler(productDB)

	userDB := database.NewUserDB(db)
	auth := jwtauth.New("HS256", []byte(authConfiguration.JwtSecret()), nil)
	userHandler := handlers.NewUserHandler(userDB, auth, authConfiguration.JwtExpiresIn())

	r := chi.NewRouter()
	r.Use(middleware.Recoverer) // gracefull handle panic errors in my route
	r.Use(middleware.Logger)    // add a Logger Middleware
	r.Use(MyOwnMiddleware)      // using my own middleware

	r.Route("/products", func(router chi.Router) {
		router.Use(jwtauth.Verifier(auth)) // insert the token in the Context
		router.Use(jwtauth.Authenticator)  // authenticate the use
		router.Get("/", productHandler.ListProducts)
		router.Post("/", productHandler.CreateProduct)
		router.Get("/{id}", productHandler.GetProduct)
		router.Put("/{id}", productHandler.UpdateProduct)
		router.Delete("/{id}", productHandler.DeleteProduct)
	})

	r.Get("/docs/*", httpSwagger.Handler(httpSwagger.URL("http://localhost:8080/docs/doc.json")))

	r.Post("/users", userHandler.Create)
	r.Post("/users/jwt", userHandler.GetJwt)
	http.ListenAndServe(":8080", r)

}

func MyOwnMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		println("MyOwnMiddleware")
		next.ServeHTTP(w, r)
	})
}
