POST http://localhost:8080/products HTTP/1.1
Content-Type: application/json

{
  "name": "My Product",
  "price": "100"
}

###
GET http://localhost:8080/products?page=0&limit=10&sort=id HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDgzOTYxNjUsInN1YiI6IjYzYmMwNWU4LWRhZGYtNGFhZi04M2NlLWE4YTE1YjI2MjZkMSJ9.sZgPvv_UKJMIgRbouG6WblEag-kDnXxwdJTjEZr2OmI

###

GET http://localhost:8080/products/b595937e-1e1e-4892-9df8-ff946fb0993d


###

PUT http://localhost:8080/products/b595937e-1e1e-4892-9df8-ff946fb0993d
Content-Type: application/json

{
  "name": "My Product updated",
  "price": 100
}

###

DELETE http://localhost:8080/products/b595937e-1e1e-4892-9df8-ff946fb0993d